_HYPE_LEVEL_PREVIEW_HTML = """<section data-component="hype-level-preview" class="card hypePreviewCard"><div class="toolbar"><div><div class="eyebrow">Hype Level Preview</div><h2>Capacity Delta Preview</h2><p>Preview replica changes before creating a Change Request</p></div><div class="filters"><select id="hypeProfile"><option value="ecp">ecp</option></select><select id="hypeTargetLevel"><option value="low">low</option><option value="medium" selected>medium</option><option value="high">high</option></select><button class="btn" id="hypePreviewButton" type="button">Preview</button></div></div><section class="hypePreviewGrid"><div class="kpi"><span>Current Level</span><strong id="hypeCurrentLevel">-</strong><small id="hypeNamespace">namespace</small></div><div class="kpi"><span>Target Level</span><strong id="hypeTargetLevelKpi">-</strong><small id="hypeProfileLabel">profile</small></div><div class="kpi"><span>Services</span><strong id="hypeServiceCount">-</strong><small>KEDA / statefulset flagged</small></div><div class="kpi"><span>Total Delta</span><strong id="hypeTotalDelta">-</strong><small id="hypeDirection">preview only</small></div></section><div class="tableMeta"><span id="hypePreviewMeta">Loading hype level preview via inventory...</span><span>reads from scanned inventory objects</span></div><div class="tableWrap hypeTableWrap"><table class="table hypeTable"><thead><tr><th>Service</th><th>Current</th><th>Target</th><th>Delta</th><th>Risk Flags</th></tr></thead><tbody id="hypeServiceRows"><tr><td colspan="5" class="empty">Loading preview...</td></tr></tbody></table></div><div class="stageHint" style="margin-top:12px"><b>Preview mode:</b> computes capacity delta from hype level inventory objects. Create a separate Change Request to apply.</div></section>"""

_HYPE_LEVEL_PREVIEW_SCRIPT = """function renderHypeRiskFlags(flags){const list=flags||[];return list.length?list.map(flag=>`<span class="riskFlag">${esc(flag)}</span>`).join(''):'<span class="muted">none</span>';}
function hypeDeltaClass(delta){if(delta>0)return 'deltaUp';if(delta<0)return 'deltaDown';return 'deltaFlat';}
async function loadHypeLevelPreview(){const qs=new URLSearchParams();qs.set('resource_type','k8s_hype_profile');qs.set('component','hypelevel');hypePreviewMeta.textContent='Loading hype preview...';const res=await api('/inventory/objects?'+qs.toString());if(!res.items||!res.items.length){hypePreviewMeta.textContent='No hype level objects found. Run inventory scan first.';hypeServiceRows.innerHTML='<tr><td colspan="5" class="empty">No hype level data</td></tr>';return;}const items=res.items;const groups={};for(const item of items){const profile=item.scope.profile||'unknown';const svcName=item.display_name;const svcKey=profile+':'+svcName;if(!groups[svcKey])groups[svcKey]=item;}const svcList=Object.values(groups);const targetLevel=hypeTargetLevel.value;let totalCurrent=0,totalTarget=0;hypeServiceRows.innerHTML=svcList.map(item=>{const spec=item.spec||{};const current=parseInt(spec[targetLevel])||0;const orig=parseInt(spec.medium)||current;const delta=current-orig;totalCurrent+=orig;totalTarget+=current;const flags=[];if(spec.KEDA)flags.push('keda_scaled_object');if(spec.statefulset)flags.push('statefulset');return`<tr><td><div class="cellMain"><b>${esc(item.display_name)}</b><div class="muted mono">max ${esc(spec.max||'-')}</div></div></td><td>${orig}</td><td>${current}</td><td><span class="${hypeDeltaClass(delta)}">${delta>0?'+':''}${delta}</span></td><td><div class="riskFlags">${renderHypeRiskFlags(flags)}</div></td></tr>`;}).join('')||'<tr><td colspan="5" class="empty">No services found</td></tr>';const totalDelta=totalTarget-totalCurrent;hypeCurrentLevel.textContent='medium (baseline)';hypeTargetLevelKpi.textContent=targetLevel;hypeServiceCount.textContent=svcList.length;hypeTotalDelta.textContent=(totalDelta>0?'+':'')+totalDelta;hypeTotalDelta.className=hypeDeltaClass(totalDelta);hypeDirection.textContent=totalDelta>0?'scale_up':totalDelta<0?'scale_down':'no_change';hypePreviewMeta.textContent=`${svcList.length} services · ${totalCurrent} -> ${totalTarget} replicas`;}
function bindHypeLevelPreviewEvents(){hypeProfile.addEventListener('change',loadHypeLevelPreview);hypeTargetLevel.addEventListener('change',loadHypeLevelPreview);hypePreviewButton.addEventListener('click',loadHypeLevelPreview);}
"""


def render_hype_level_preview_html():
    return _HYPE_LEVEL_PREVIEW_HTML


def hype_level_preview_script():
    return _HYPE_LEVEL_PREVIEW_SCRIPT
