_DASHBOARD_KPI_HTML = """<section class="grid4"><div class="kpi"><span>Total Objects</span><strong id="totalObjects">-</strong><small>from scanned repo</small></div><div class="kpi"><span>Resource Types</span><strong id="resourceTypes">-</strong><small>adapter normalized</small></div><div class="kpi"><span>Environments</span><strong id="envs">-</strong><small>detected scopes</small></div><div class="kpi"><span>Scan Errors</span><strong id="errors">-</strong><small>resilient parsing</small></div></section>"""

_INVENTORY_DASHBOARD_HTML = """<div data-component="inventory-dashboard"><section class="analytics"><div class="card"><div class="eyebrow">Resource Mix</div><div class="bars" id="resourceBars"><div class="empty">Loading...</div></div></div><div class="card"><div class="eyebrow">Environment Distribution</div><div class="bars" id="envBars"><div class="empty">Loading...</div></div><div class="eyebrow" style="margin-top:18px">Boundaries</div><div class="chips" id="boundaryChips"></div></div></section>
<section class="main"><div class="card inventoryCard"><div class="toolbar"><div><h2>Terraform Resources</h2><p>Scanned Terraform resources &middot; click row to view detail</p></div><div class="filters"><select id="typeFilter"><option value="">All types</option></select><select id="envFilter"><option value="">All envs</option></select><input id="qFilter" placeholder="Search id/name" /></div></div><div class="tableMeta"><span id="objectCount">Loading objects...</span><span>Showing first 120 rows</span></div><div class="tableWrap"><table class="table"><thead><tr><th>Resource</th><th>Type</th><th>Env</th><th>Boundary</th><th>Source</th></tr></thead><tbody id="rows"><tr><td colspan="5" class="empty">Loading...</td></tr></tbody></table></div></div><aside class="card detailCard"><div class="detailHead"><div><div class="eyebrow">Selected detail</div><h2 id="detailTitle">No object selected</h2></div><span class="pill" id="detailType">idle</span></div><pre class="detail mono" id="detail">Select a resource from the table.</pre></aside></section></div>"""

_INVENTORY_DASHBOARD_SCRIPT = """function barRows(items,labelKey){const max=Math.max(1,...items.map(x=>x.count));return items.map(x=>`<div class="barRow"><div class="barLabel" title="${esc(x[labelKey])}">${esc(x[labelKey])}</div><div class="barTrack"><div class="barFill" style="width:${Math.max(5,Math.round(x.count/max*100))}%"></div></div><div class="barCount">${x.count}</div></div>`).join('')||'<div class="empty">No data</div>';}
async function loadSummary(){const h=await api('/api/health');health.textContent=h.status;const s=await api('/inventory/summary');const k=s.kpis;totalObjects.textContent=k.total_objects;resourceTypes.textContent=k.resource_types;envs.textContent=k.environments;errors.textContent=k.errors;}
async function loadOverview(){const o=await api('/inventory/overview');resourceBars.innerHTML=barRows(o.top_resource_types,'resource_type');envBars.innerHTML=barRows(o.env_distribution,'env');boundaryChips.innerHTML=(o.boundary_distribution||[]).map(x=>`<span class="chip">${esc(x.boundary||x.env)} <b>${x.count}</b></span>`).join('');typeFilter.innerHTML='<option value="">All types</option>'+(o.top_resource_types||[]).map(x=>`<option value="${esc(x.resource_type)}">${esc(x.resource_type)}</option>`).join('');envFilter.innerHTML='<option value="">All envs</option>'+(o.env_distribution||[]).map(x=>`<option value="${esc(x.env)}">${esc(x.env)}</option>`).join('');}
async function loadAdapters(){const a=await api('/adapters');adapters.innerHTML=(a.items||[]).slice(0,12).map(x=>`<span class="chip">${esc(x.resource_type)}</span>`).join('');}
async function loadObjects(){const qs=new URLSearchParams();if(typeFilter.value)qs.set('resource_type',typeFilter.value);if(envFilter.value)qs.set('env',envFilter.value);if(qFilter.value)qs.set('q',qFilter.value);const payload=await api('/inventory/objects'+(qs.toString()?'?'+qs.toString():''));const all=payload.items;const items=all.slice(0,120);objectCount.textContent=`${all.length} matched objects`;rows.innerHTML=items.length?items.map(x=>`<tr onclick="loadDetail('${encodeURIComponent(x.id)}')"><td><div class="cellMain"><b>${esc(x.display_name)}</b><div class="muted mono" title="${esc(x.id)}">${esc(x.id)}</div></div></td><td><span class="pill">${esc(x.resource_type)}</span></td><td>${esc(x.scope.env)}</td><td>${esc(x.scope.boundary||(x.source||{}).boundary||'')}</td><td><div class="mono cellPath" title="${esc((x.source||{}).path||'')}">${esc((x.source||{}).path||'')}</div></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No objects. Try scanning first.</td></tr>';}
async function loadDetail(id){const d=await api('/inventory/objects/'+encodeURIComponent(id));detail.textContent=JSON.stringify(d,null,2);detailTitle.textContent=d.display_name||d.id;detailType.textContent=d.resource_type||'detail';}
function bindInventoryDashboardEvents(){typeFilter.addEventListener('change',loadObjects);envFilter.addEventListener('change',loadObjects);qFilter.addEventListener('input',()=>{clearTimeout(window.__q);window.__q=setTimeout(loadObjects,180)});}
"""


def render_dashboard_kpi_html():
    return _DASHBOARD_KPI_HTML


def render_inventory_dashboard_html():
    return _INVENTORY_DASHBOARD_HTML


def inventory_dashboard_script():
    return _INVENTORY_DASHBOARD_SCRIPT
