_TEMPLATE_CATALOG_HTML = """<section data-component="template-catalog" class="card templateCatalogCard"><div class="toolbar"><div><div class="eyebrow">Template Catalog</div><h2>Standard Resource Templates</h2><p>Standardized Terraform resource templates — EC2, RDS, VPC, S3, IAM, CloudWatch &amp; more</p></div><div class="filters"><select id="templateProviderFilter"><option value="">All providers</option><option value="AWS">AWS</option><option value="GCP">GCP</option><option value="Azure">Azure</option></select><select id="templateResourceTypeFilter"><option value="">All resource types</option><option value="aws_instance">aws_instance</option><option value="aws_db_instance">aws_db_instance</option><option value="aws_vpc">aws_vpc</option><option value="aws_s3_bucket">aws_s3_bucket</option><option value="aws_iam_role">aws_iam_role</option><option value="aws_eks_cluster">aws_eks_cluster</option></select><select id="templateCapabilityFilter"><option value="">All capabilities</option><option value="schema_form">schema_form</option><option value="patch_preview">patch_preview</option><option value="terraform_onboarding">terraform_onboarding</option><option value="plan_preview">plan_preview</option><option value="approval_required">approval_required</option></select><button class="btn" id="templateCatalogButton" type="button">Load</button></div></div><div class="templateCatalogMeta"><span id="templateCatalogCount">Loading templates...</span><span id="templateDraftBridgeStatus">Pick a template to prefill Resource Management</span></div><div class="templateCardGrid" id="templateCards"><div class="empty">Loading Template Registry...</div></div></section>"""

_TEMPLATE_CATALOG_SCRIPT = """function renderTemplateCapabilities(capabilities){return (capabilities||[]).map(c=>`<span class="templateCapability">${esc(c)}</span>`).join('')||'<span class="muted">none</span>';}
function renderTemplateCard(template){const terraformPath=template.terraform_template_path||'not mapped yet';const skeletonLabel=template.skeleton_enabled?'Use Template':'Prefill Draft';const skeletonAction=template.skeleton_enabled?'open-wizard':'prefill-draft';return `<article class="templateCard" data-template-id="${esc(template.id)}"><div class="templateCardHead"><div><span class="templateProvider">${esc(template.provider)}</span><h3>${esc(template.name)}</h3></div><span class="pill">${esc(template.status)}</span><span class="pill skeleton-tag" style="${template.skeleton_enabled?'background:rgba(194,239,78,.15);border-color:rgba(194,239,78,.3)':'display:none'}">skeleton</span></div><div class="templateResourceType mono">${esc(template.resource_type)}</div><p>${esc(template.notes||'')}</p><div class="templatePathGrid"><div><span>Schema</span><code>${esc(template.source_schema_path)}</code></div><div><span>Desired state</span><code>${esc(template.desired_state_path_rule)}</code></div><div><span>Terraform template</span><code>${esc(terraformPath)}</code></div><div><span>Approval</span><code>${esc(template.approval_policy)}</code></div></div><div class="templateCapabilityRow">${renderTemplateCapabilities(template.capabilities)}</div><div class="templateActionRow"><button class="btn" type="button" data-template-action="${esc(skeletonAction)}" data-template-id="${esc(template.id)}">${esc(skeletonLabel)}</button><span class="muted">${template.skeleton_enabled?'opens Skeleton Wizard':'fills Resource Management form'}</span></div></article>`;}
function prefillDraftFromTemplate(templateId){const cw=document.querySelector('[data-component="change-workspace"]');if(!cw){templateDraftBridgeStatus.textContent='Navigate to a capability page to create changes.';return false;}const dct=document.getElementById('draftChangeType');const doi=document.getElementById('draftObjectId');const dr=document.getElementById('draftReason');const dmr=document.getElementById('draftMaxReplicas');const pp=document.getElementById('patchPreview');if(!dct||!doi||!dr||!pp){templateDraftBridgeStatus.textContent='Change form elements not found on this page.';return false;}dct.value='terraform_resource_update';doi.value='tf/resources/dev/'+esc(templateId)+'/my-resource';if(dmr)dmr.value='';dr.value='template catalog: update '+esc(templateId)+' resource';cw.scrollIntoView({behavior:'smooth',block:'start'});pp.textContent='Template Catalog filled a draft for '+esc(templateId)+'. Submit Create Draft to generate patch diff.';templateDraftBridgeStatus.textContent='Draft prefilled from template: '+esc(templateId);return true;}
async function loadTemplateCatalog(){const qs=new URLSearchParams();if(templateProviderFilter.value)qs.set('provider',templateProviderFilter.value);if(templateResourceTypeFilter.value)qs.set('resource_type',templateResourceTypeFilter.value);if(templateCapabilityFilter.value)qs.set('capability',templateCapabilityFilter.value);templateCatalogCount.textContent='Loading templates...';const res=await api('/templates'+(qs.toString()?'?'+qs.toString():''));if(res.error){templateCatalogCount.textContent=res.error.detail||res.error.message||'error';templateCards.innerHTML='<div class="empty">Error loading templates</div>';return;}const items=res.items||[];templateCatalogCount.textContent=`${items.length} templates matched`;templateCards.innerHTML=items.length?items.map(renderTemplateCard).join(''):'<div class="empty">No templates matched.</div>';}
function bindTemplateCatalogEvents(){if(typeof templateProviderFilter!=='undefined'){templateProviderFilter.addEventListener('change',loadTemplateCatalog);templateResourceTypeFilter.addEventListener('change',loadTemplateCatalog);templateCapabilityFilter.addEventListener('change',loadTemplateCatalog);templateCatalogButton.addEventListener('click',loadTemplateCatalog);templateCards.addEventListener('click',event=>{const btn=event.target.closest('[data-template-action="prefill-draft"]');if(btn&&!btn.disabled){prefillDraftFromTemplate(btn.dataset.templateId);return;}const wizardBtn=event.target.closest('[data-template-action="open-wizard"]');if(wizardBtn&&!wizardBtn.disabled){openSkeletonWizard(wizardBtn.dataset.templateId);}});}}
"""


def render_template_catalog_html():
    return _TEMPLATE_CATALOG_HTML


def template_catalog_script():
    return _TEMPLATE_CATALOG_SCRIPT
