import logging
import uuid
from datetime import datetime, timezone

from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.projects.service import ProjectService
from app.domain.skeletons.models import SkeletonPreview, SkeletonResult
from app.domain.skeletons.registry import SkeletonRegistry
from app.domain.skeletons.renderer import TemplateRenderer
from app.domain.skeletons.repository import ScaffoldRepository
from app.domain.skeletons.validation import ParameterValidator
from app.infrastructure.adapters.registry import InfrastructureAdapterRegistry

logger = logging.getLogger(__name__)


class SkeletonService:
    def __init__(
        self,
        skeleton_registry: SkeletonRegistry,
        infra_registry: InfrastructureAdapterRegistry,
        db: AsyncSession | None = None,
    ):
        self._registry = skeleton_registry
        self._infra = infra_registry
        self._db = db
        self._renderer = TemplateRenderer()
        self._validator = ParameterValidator()

    def preview(self, template_id: str, params: dict) -> SkeletonPreview:
        template = self._registry.get(template_id)
        if template is None:
            raise ValueError(f"skeleton template not found: {template_id}")
        validation = self._validator.validate(template.parameter_schema, params)
        if not validation.valid:
            error_details = "; ".join(
                f"{e['field']}: {e['error']}" for e in validation.errors
            )
            raise ValueError(f"Parameter validation failed: {error_details}")
        return self._renderer.render_tree(template, params)

    async def apply(
        self,
        template_id: str,
        params: dict,
        project_id: str,
        author: str = "sre-user",
    ) -> SkeletonResult:
        template = self._registry.get(template_id)
        if template is None:
            return SkeletonResult(success=False, error=f"skeleton template not found: {template_id}")

        # Validate params before preview
        validation = self._validator.validate(template.parameter_schema, params)
        if not validation.valid:
            error_details = "; ".join(
                f"{e['field']}: {e['error']}" for e in validation.errors
            )
            raise ValueError(f"Parameter validation failed: {error_details}")

        preview = self.preview(template_id, params)

        if self._db is None:
            return SkeletonResult(
                success=False, preview=preview,
                capability_id=template.capability_id,
                error="database session required for apply",
            )

        proj_svc = ProjectService(self._db)
        project = await proj_svc.get_project(project_id)
        if project is None:
            return SkeletonResult(
                success=False, preview=preview,
                capability_id=template.capability_id,
                error=f"project not found: {project_id}",
            )

        adapter_name = project.get("git_adapter", "github")
        adapter = self._infra.get_git_adapter(adapter_name)
        if adapter is None:
            return SkeletonResult(
                success=False, preview=preview,
                capability_id=template.capability_id,
                error=f"git adapter not found: {adapter_name}",
            )

        git_config = project.get("git_config", {})
        suffix = uuid.uuid4().hex[:8]
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        branch = f"skeleton/{template_id}/{timestamp}-{suffix}"

        repo = ScaffoldRepository(self._db)
        files_generated = [
            {"path": sf["path"], "filename": sf["filename"], "file_type": sf["file_type"]}
            for sf in preview.files
        ]

        try:
            await adapter.ensure_cloned(git_config)
            await adapter.create_feature_branch(git_config, branch, base="main")

            for sf in preview.files:
                msg = f"skeleton({template_id}): add {sf['filename']}"
                await adapter.apply_and_commit(git_config, branch, sf["path"], sf["content"], msg)

            await adapter.push(git_config, branch)
            commit_sha = await adapter.get_head_sha(git_config)

            title = f"[Skeleton] {template.name} scaffold by {author}"
            body_lines = [
                f"Template: {template.name} ({template.render_mode.upper()})",
                f"Provider: {template.provider}",
                f"Generated by: {author}",
                "",
                "Parameters:",
            ]
            for k, v in params.items():
                body_lines.append(f"  {k}: {v}")
            body_lines.append("")
            body_lines.append("Files generated:")
            for sf in preview.files:
                body_lines.append(f"  - {sf['path']}")

            pr = await adapter.create_pr(git_config, branch, title, "\n".join(body_lines))

            # Record successful scaffold run
            await repo.add({
                "project_id": project_id,
                "template_id": template_id,
                "template_name": template.name,
                "provider": template.provider,
                "render_mode": template.render_mode,
                "capability_id": template.capability_id,
                "params": params,
                "author": author,
                "status": "applied",
                "pr_url": pr.url,
                "branch": branch,
                "commit_sha": commit_sha,
                "files_generated": files_generated,
            })

            logger.info(
                "Skeleton applied: template=%s mode=%s project=%s branch=%s pr=%s",
                template_id, template.render_mode, project_id, branch, pr.url,
            )
            return SkeletonResult(
                success=True,
                preview=preview,
                pr_url=pr.url,
                branch=branch,
                commit_sha=commit_sha,
                capability_id=template.capability_id,
            )
        except Exception as exc:
            logger.exception("Skeleton apply failed")

            # Record failed scaffold run
            await repo.add({
                "project_id": project_id,
                "template_id": template_id,
                "template_name": template.name,
                "provider": template.provider,
                "render_mode": template.render_mode,
                "capability_id": template.capability_id,
                "params": params,
                "author": author,
                "status": "failed",
                "branch": branch,
                "files_generated": files_generated,
                "error_message": str(exc),
            })

            return SkeletonResult(
                success=False, preview=preview,
                capability_id=template.capability_id,
                error=str(exc),
            )
