apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sandbox
data:
  nginx.conf: |
    worker_processes 2;
    events {
        worker_connections 512;
    }
  max_clients: "500"
  log_level: info
